name: AML
main: top.aot.ml.MListMain
version: 2.2.0
softdepend: [PlaceholderAPI]

commands:
   aml:
      description: open
      usage: /aml
   amrc:
      description: open
      usage: /amrc
   asp:
      description: open
      usage: /asp
   acp:
      description: open
      usage: /acp
   acpt:
      description: open
      usage: /acpt